services:
  wysi:
    build:
      context: .
    environment:
      OSU_ID: ${OSU_ID}
      OSU_SECRET: ${OSU_SECRET}
      OSU_REDIRECT: ${OSU_REDIRECT}
      MONGO_URI: ${MONGO_URI}
      CROWDIN_ID: ${CROWDIN_ID}
      CROWDIN_SECRET: ${CROWDIN_SECRET}
      PORT: ${PORT}
    ports:
      - '4000:4000'
